import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { verifyFinalWorktree } from "./verify-final-worktree.mjs";

const repositoryRoot = path.resolve(new URL("..", import.meta.url).pathname);
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

function command(executable, args, { cwd = repositoryRoot, binary = false, input = undefined } = {}) {
  const result = spawnSync(executable, args, { cwd, input, encoding: binary ? null : "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (result.error || result.status !== 0) throw new Error(`${executable} ${args.join(" ")} failed\n${result.error ?? ""}${result.stdout ?? ""}${result.stderr ?? ""}`);
  return result;
}

function parseArgs(argv) {
  const result = {};
  const names = { "--receipt": "receipt", "--worktree": "worktree", "--repo": "repo", "--base": "base", "--branch": "branch", "--title": "title", "--task-url": "taskUrl" };
  for (let index = 0; index < argv.length; index += 2) {
    const name = names[argv[index]]; const value = argv[index + 1];
    if (!name || !value) throw new Error(`invalid publication argument ${argv[index]}`);
    result[name] = value;
  }
  for (const required of Object.values(names)) if (!result[required]) throw new Error(`${required} is required`);
  result.receipt = path.resolve(result.receipt); result.worktree = path.resolve(result.worktree);
  return result;
}

function prBody(receipt, liveReceiptSha256, taskUrl) {
  return `Generated by Praxis v1 repository-steward.

Task: ${taskUrl}
Base commit: ${receipt.base_revision}
Praxis candidate: ${receipt.candidate_commit}
Application ID: ${receipt.application_id}
Application WASM SHA-256: ${receipt.application_wasm_sha256}
Live receipt SHA-256: ${liveReceiptSha256}
Final diff SHA-256: ${receipt.final_diff_sha256}
Released stack:
- Agent v2.5.0
- Boundary v1.5.0
- World v3.1.3
- world-host v1.0.1
- world-capabilities v2.3.2

Verification:
- receiver-authorized paths only
- receiver-approved digest-bound writes only
- zig build check --summary all passed after the final mutation
- independent pre-publication verification passed
- no manual code edits between Agent completion and commit

This is a draft and requires ordinary human review. The receipt does not claim
universal correctness, hostile-host protection, prompt-injection immunity, or
exactly-once external effects.
`;
}

export async function publishDraft(options) {
  const receiptBytes = await readFile(options.receipt); const receipt = JSON.parse(receiptBytes.toString("utf8"));
  if (receipt?.praxis_format !== 1 || receipt.mode !== "live" || receipt.terminal_status !== "completed" || !receipt.independent_verifier_passed) throw new Error("verified successful live receipt required");
  if (receipt.repository !== options.repo) throw new Error("publication repository mismatch");
  const runRoot = path.dirname(options.worktree); const metadata = JSON.parse(await readFile(path.join(runRoot, "run-metadata.json"), "utf8"));
  if (metadata.format !== "praxis-private-run-metadata/v1" || metadata.repository !== options.repo || metadata.baseRevision !== receipt.base_revision) throw new Error("private run metadata mismatch");
  const verifier = await verifyFinalWorktree({
    receipt, worktree: options.worktree, candidate: metadata.candidate, policy: metadata.policy,
    zigExecutable: metadata.zigExecutable, approvalRoot: path.join(runRoot, "approvals"), temporaryHome: path.join(runRoot, "publication-verify-home"),
  });
  assert.equal(verifier.final_diff_sha256, receipt.final_diff_sha256);
  command("gh", ["auth", "status"]);
  assert.equal(command("git", ["rev-parse", "HEAD"], { cwd: options.worktree }).stdout.trim(), receipt.base_revision);
  command("git", ["switch", "-c", options.branch, receipt.base_revision], { cwd: options.worktree });
  command("git", ["add", "--", ...receipt.changed_paths], { cwd: options.worktree });
  const staged = command("git", ["diff", "--cached", "--name-only"], { cwd: options.worktree }).stdout.trim().split("\n").filter(Boolean);
  assert.deepEqual(staged, receipt.changed_paths);
  command("git", ["-c", "user.name=Praxis Operator", "-c", "user.email=praxis@users.noreply.github.com", "commit", "-m", options.title], { cwd: options.worktree });
  const headRevision = command("git", ["rev-parse", "HEAD"], { cwd: options.worktree }).stdout.trim();
  const publishedDiff = command("git", ["diff", "--binary", "--no-ext-diff", "--full-index", receipt.base_revision, headRevision, "--", ...receipt.changed_paths], { cwd: options.worktree, binary: true }).stdout;
  assert.equal(sha256(publishedDiff), receipt.final_diff_sha256);
  command("git", ["push", "--set-upstream", "origin", options.branch], { cwd: options.worktree });
  const liveReceiptSha256 = sha256(receiptBytes);
  const body = prBody(receipt, liveReceiptSha256, options.taskUrl);
  command("gh", ["pr", "create", "--repo", options.repo, "--base", options.base, "--head", options.branch, "--title", options.title, "--body-file", "-", "--draft"], { cwd: options.worktree, input: body });
  const pr = JSON.parse(command("gh", ["pr", "view", options.branch, "--repo", options.repo, "--json", "number,url,isDraft,headRefOid"]).stdout);
  assert.equal(pr.isDraft, true); assert.equal(pr.headRefOid, headRevision);
  const publication = {
    praxis_format: 1, mode: "publication", repository: options.repo, base_revision: receipt.base_revision,
    head_revision: headRevision, branch: options.branch, pull_request_number: pr.number, pull_request_url: pr.url,
    draft: pr.isDraft, candidate_commit: receipt.candidate_commit, application_id: receipt.application_id,
    live_receipt_sha256: liveReceiptSha256, final_diff_sha256: receipt.final_diff_sha256,
    published_tree_matches_verified_diff: true,
  };
  const target = path.join(repositoryRoot, "conformance/praxis-v1/receipts/publication.json");
  await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, `${JSON.stringify(publication, null, 2)}\n`);
  return publication;
}

if (import.meta.main) {
  const publication = await publishDraft(parseArgs(process.argv.slice(2)));
  process.stdout.write(`praxis_draft_pr=${publication.pull_request_url}\n`);
}

export const _publishInternals = { parseArgs, prBody };
